// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quizyy.Model;

#nullable disable

namespace Quizyy.Migrations
{
    [DbContext(typeof(MyBaseContext))]
    [Migration("20231103202519_test2")]
    partial class test2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Quizyy.Model.FlashCardsModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("concept")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("definition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("FlashCards");
                });

            modelBuilder.Entity("Quizyy.Model.WriteModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("incorrectans1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("incorrectans2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("incorrectans3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Writes");
                });
#pragma warning restore 612, 618
        }
    }
}
